### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by eggplants** [hakatashi/unicode-map#6]
Do you have any plans to follow Unicode ~13.0?

**Comment by hakatashi** [comment]
Currently there's no plan for supporting further codepoints (maintaining this repository requires considerable amount of work). Maybe I will work on this repo when I have time and interests in the future.

Contributions are always welcome however.

**Comment by eggplants** [comment]
I have implemented support for Unicode 17.0, including the replacement of Livescript and other obsolete dependencies, as part of unicode-map v4 in my forked repo.

- https://github.com/eggplants/unicode-map/releases/tag/v4.0.3
- https://egpl.dev/unicode-map/
- https://github.com/eggplants/unicode-map/compare/201804190817...v4.0.3

Since the changes were so significant, it seems difficult to submit a PR, but are there any plans for maintenance of this repo?

**Comment by hakatashi** [comment]
Awesome work! It really makes me happy to see my ideas carried forward in this way.

I haven't personally been keeping up with Unicode specifications for quite a while now, so I don't have any immediate plans to actively maintain this repository myself. Because of that, I’m open to fully adopting your changes—even if they involve major overhauls—and a pull request would be very welcome. I’ll plan to take a look through your code over the next few days (or maybe months? :)).

Also, depending on your interests and availability, if you'd like to continue working on this project moving forward, I'd be more than happy to invite you as a maintainer to this repository and completely delegate releases and maintenance to you. Please feel free to think it over and let me know!

**Comment by eggplants** [comment]
Thank you for your reply. 

Once you’ve reviewed and are satisfied with them, I plan to rewrite the changes I made to the fork (such as the eggplants/unicode-map link) and submit a pull request.

If I can be granted maintainer privileges after that pull request is merged, I’d be happy to accept them.

**Comment by eggplants** [comment]
@hakatashi I've created #7 for review easily. Please take a look 🙏
